Resources:
  MonBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21088
  MonParametreSSM:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/mon-bucket-s3/nom"
      Type: "String"
      Value: !Ref MonBucketS3
      Description: "Nom du bucket S3 nouvellement créé"

  MonParametreARNSSM:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/mon-bucket-s3/arn"
      Type: "String"
      Value: !GetAtt MonBucketS3.Arn
      Description: "ARN du bucket S3 nouvellement créé"
